### ISSUE TITLE
Figure 2: 293T-ACE2 cells

### ISSUE THREAD

**Issue by jbloom** [jbloomlab/SARS-CoV-2_lentiviral_pseudotype#2]
(How made - maybe not needed), Flow plot verifying expression, Figure with just microscopy showing ZsGreen infection in 293T versus 293T-ACE2.

(Do we have any data justifying 293T-ACE2 over Vero-E6?)

**Comment by khdcrawford** [comment]
Completed. 

Became Fig. 2 of manuscript.
